### ISSUE TITLE
inexact numbers

### ISSUE THREAD

**Issue by Checkmate6659** [LoicViennois/KSP-DeltaV-Planner#14]
Some numbers are inexact. For example, I was able to do a return from the Mun to Kerbin in less than 1km/s (with aerobraking), despite that the tool reports 1750m/s. I guess the reason could be that the way I aerobraked didn't involve circularizing, and I just aerobraked from an elliptical orbit, and kept aerobraking until my apoapsis was contained in the atmosphere, at which point I landed. So from the moment your orbit intersects the atmosphere, and if you don't get unhelpful Mun gravity assists, then the delta-V required to land should be 0.

**Comment by LoicViennois** [comment]
Hi, this is due to the fact that the Aerobraking option is not applied to the step "Transit from Mun low orbit to Kerbin low orbit", while in fact you can actually use aerobraking to lower the Δv needed for this step.
To be more accurate, the planner should split the Transit into "from low orbit to elliptical orbit" + "transit" + "circularization at destination", with the possibility to apply the aerobraking at both ""transit"  and "circularization".
Thank you for your feedback, I will the think about adding this feature.

This is related to #4
